MONGODB_URL: "mongodb://<user_name>:<password>@<external_IP_of_VM>:<mongodb_port>/"
BATCH_SIZE: 1000
POOL_SIZE: 40
TIMEOUT: 5
LOGGING:
  level: INFO
  log_file: logs/data_enrichment.log
  to_console: true
CREDENTIAL: glamira-project-464503-a80775406a71.json